#!/bin/sh
#Copyright [2018] [jc3wish]

#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

#http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

bin_dir=
pid_file=
config_file=

mode=$1    # start or stop or restart

basepath=$(cd `dirname $0`; pwd)

function __readINI() {
 INIFILE=$1; SECTION=$2; ITEM=$3
 #echo $ITEM
 #_readIni=`awk -F '=' '/\['$SECTION'\]/{a=1}a==1&&$1~/'$ITEM'/{print $2;exit}' $INIFILE`
 _readIni=`cat Bifrost.ini|awk 'BEGIN{FS="=";OFS=":";}/\'$SECTION'\]/,/\[.*[^('$SECTION')].*\]/{gsub(/[[:blank:]]*/,"",$1);if(NF==2 && $1=="'$ITEM'"){gsub(/^[[:blank:]]*/,"",$2);gsub(/[[:blank:]]*$/,"",$2);print $2;}}'`
 echo ${_readIni}
}

if test -z "$bin_dir"
then
  bin_dir="$basepath"
fi

if test -z "$config_file"
then
  config_file="$basepath/Bifrost.ini"
fi

if test -z "$pid_file"
then
  pid_file=( $( __readINI /data/windows/gocode/src/github.com/Bifrost/Bifrost.ini Bifrostd pid ) ) 
fi

if test -z "$pid_file"
then
  pid_file="$basepath/Bifrost.pid"
fi

case "$mode" in
  'start')
    # Start daemon
    cd $bin_dir

    #echo "Starting Bifrost"
    if test -x $bin_dir/Bifrost
    then
      $bin_dir/Bifrost -d true -config "$config_file"
      exit 0
    else
      echo "Couldn't find Bifrost server ($bin_dir/Bifrost)"
    fi
    ;;

  'stop')
    # Stop daemon. We use a signal here to avoid having to know the

    if test -s "$pid_file"
    then
      bifrost_pid=`cat "$pid_file"`

      if (kill -0 $bifrost_pid 2>/dev/null)
      then
        echo "Shutting down Bifrost"
        kill $bifrost_pid
      else
        echo "Bifrost server process #$bifrost_pid is not running!"
        rm "$pid_file"
      fi
      exit 0
    else
      echo "Bifrost server PID file could not be found!"
      exit 1
    fi
    ;;

  'restart')
    # Stop the service and regardless of whether it was
    # running or not, start it again.
    if $0 stop; then
      $0 start
    else
      echo "Failed to stop running server, so refusing to try to start."
      exit 1
    fi
    ;;

  'status')
    # First, check to see if pid file exists
    if test -s "$pid_file" ; then 
      bifrost_pid=`cat "$pid_file"`
      if kill -0 $bifrost_pid 2>/dev/null ; then 
        echo "Bifrost running ($bifrost_pid)"
        exit 0
      else
        echo "Bifrost is not running, but PID file exists"
        exit 1
      fi
    fi
    ;;
    *)
      # usage
      basename=`basename "$0"`
      echo "Usage: $basename  {start|stop|restart|status}  [ Bifrost server options ]"
      exit 1
    ;;
esac

exit 0
