version: '3.8'
services:
  sync:
    image:  golang:1.14.2-buster
    networks:
      - share
    ports:
      - "21037:21036"
    volumes:
      - .:/sync
    working_dir: /sync/linux
    entrypoint: ./Bifrost-server start
networks:
  share: